CREATE TABLE [dbo].[Employee]
(
	[Id] UNIQUEIDENTIFIER NOT NULL UNIQUE PRIMARY KEY, 
    [Email] NVARCHAR(128) NOT NULL UNIQUE, 
    [FirstName] NVARCHAR(128) NOT NULL, 
    [LastName] NVARCHAR(128) NOT NULL
)
